{{- if .Values.applier.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "applier.name" . }}
  labels:
    {{- include "applier.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "applier.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print $.Template.BasePath "/applier/applier-configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "applier.selectorLabels" . | nindent 8 }}
        helm.sh/chart-version: {{ .Chart.Version }}
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: {{ include "optimize-live.fullname" . }}-docker
      serviceAccountName: {{ include "optimize-live.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "applier.name" . }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.applier.image.repository }}:{{ .Values.applier.image.tag }}
        imagePullPolicy: {{ .Values.applier.image.pullPolicy }}
        resources:
            {{- toYaml .Values.applier.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /config.yaml
          name: applierconfig
          subPath: config.yaml
      volumes:
      - configMap:
          defaultMode: 420
          name: applier
        name: applierconfig
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
