apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
    component: grafana
  namespace: {{ include "optimize-live.namespace" . }}
data:
  grafana.ini: |-
    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [auth]
    disable_login_form = true

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = {{ if .Values.debug -}} Admin {{- else -}} Viewer {{- end }}
    hide_version = true

    [alerting]
    enabled = false

    [explore]
    enabled = false

    [metrics]
    enabled = false

    [expressions]
    enabled = false
