{{- if .Values.grafana.enabled  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    component: grafana
  namespace: {{ include "optimize-live.namespace" . }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - access: ""
      editable: false
      isDefault: false
      name: "empty"
      orgId: 1
      type: prometheus
      url: {{ .Values.metricsURL }}
      version: 1
{{- end }}